[project]
name = "OrnaCodexCrawler"
version = "2.0.0"
description = "Crawler for Orna Codex"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "glom>=25.12.0",
    'scrapy',
    'tomlkit',
]
license = "MIT"
